package com.github.jacekpoz.common;

import lombok.Getter;
import lombok.Setter;

import javax.swing.*;
import java.io.Serializable;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class Chat implements Serializable {
    private static final long serialVersionUID = -8973712096190274407L;
    private final @Getter
    long id;
    private @Getter @Setter
    String name;
    private @Getter
    List<UserInfo> members;
    private @Getter
    List<Long> messageIDs;
    private final @Getter
    Timestamp dateCreated;
    private @Getter
    long messageCounter;

    public Chat(long chatID, String chatName, Timestamp created, long mCounter) {
        id = chatID;
        name = chatName;
        members = new ArrayList<>();
        messageIDs = new ArrayList<>();
        dateCreated = created;
        messageCounter = mCounter;
    }

    public void sortMessages() {
        messageIDs.sort(Comparator.naturalOrder());
    }

    /*
     * auto generated by intellij
     * **************************
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Chat that = (Chat) o;
        return id == that.id;
    }

    @Override
    public String toString() {
        return "Chat{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", dateCreated=" + dateCreated +
                '}';
    }
    /*
     * **************************
     */
}
