package com.github.jacekpoz.common;

import lombok.Getter;

import javax.swing.*;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

public class Message implements Serializable {

    private static final long serialVersionUID = -3347591867787345026L;
    private final @Getter long id;
    private final @Getter String content;
    private final @Getter LocalDateTime sendDate;
    private final @Getter UserInfo author;
    private transient @Getter JLabel label;

    public Message(String text, UserInfo u) {
        id = GlobalStuff.MESSAGE_COUNTER++;
        content = text;
        sendDate = LocalDateTime.now();
        author = u;

        initLabel();
    }

    public Message(String text) {
        this(text, new UserInfo(-1, "dupa", "dupa"));
    }

    public void initLabel() {
        label = new JLabel(author.getNickname() + ": " + content);

        label.setToolTipText(Util.localDateTimeToString(sendDate));
    }

    // auto generated by intellij
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Message message = (Message) o;
        return id == message.id && Objects.equals(content, message.content) && Objects.equals(sendDate, message.sendDate);
    }

    @Override
    public String toString() {
        return "Message{" +
                "messageID=" + id +
                ", content='" + content + "'" +
                ", date=" + sendDate +
                ", author=" + author +
                "}";
    }
}
