package com.github.jacekpoz.common;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class UserInfo implements Serializable {

    private static final long serialVersionUID = -4542684939965736548L;
    private @Getter final long id;
    private @Getter @Setter String nickname;
    private @Getter @Setter String hashedPassword;
    private @Getter final List<UserInfo> friends;

    public UserInfo(long userID, String userNickname, String userHashedPassword) {
        id = userID;
        nickname = userNickname;
        hashedPassword = userHashedPassword;
        friends = new ArrayList<>();
    }

    public void addFriend(UserInfo u) throws FriendException {
        if (friends.contains(u)) throw new FriendException("This user is already a friend");
        friends.add(u);
    }

    public void removeFriend(UserInfo u) throws FriendException {
        if (!friends.contains(u)) throw new FriendException("This user isn't a friend");
        friends.remove(u);
    }

    // auto generated by intellij
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        UserInfo userInfo = (UserInfo) o;
        return id == userInfo.id &&
                Objects.equals(nickname, userInfo.nickname) &&
                Objects.equals(hashedPassword, userInfo.hashedPassword) &&
                Objects.equals(friends, userInfo.friends);
    }

    @Override
    public String toString() {
        return "UserInfo{" +
                "id=" + id +
                ", nickname='" + nickname + "'" +
                ", hashedPassword='" + hashedPassword + "'" +
                "}";
    }

}
