package com.github.jacekpoz.common;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class User implements Serializable {

    private static final long serialVersionUID = -4542684939965736548L;
    @Getter
    private final long id;
    @Getter
    @Setter
    private String nickname;
    @Getter
    @Setter
    private String hashedPassword;
    @Getter
    private final List<Long> friendsIds;
    @Getter
    private final Timestamp dateJoined;

    public User(long userID, String userNickname, String userHashedPassword, Timestamp date) {
        id = userID;
        nickname = userNickname;
        hashedPassword = userHashedPassword;
        friendsIds = new ArrayList<>();
        dateJoined = date;
    }

    public void addFriend(User u) {
        if (!friendsIds.contains(u.id)) friendsIds.add(u.id);
    }

    public void addFriend(long id) {
        if (!friendsIds.contains(id)) friendsIds.add(id);
    }

    public void removeFriend(User u) {
        friendsIds.remove(u.id);
    }

    public void removeFriend(long id) {
        friendsIds.remove(id);
    }

    /*
     * auto generated by intellij
     * **************************
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User userInfo = (User) o;
        return id == userInfo.id &&
                Objects.equals(nickname, userInfo.nickname);
    }
    /*
     * **************************
     */

    @Override
    public String toString() {
        return nickname + " (ID=" + id + ")";
    }

}
