package com.github.jacekpoz.common;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class UserInfo implements Serializable {

    private static final long serialVersionUID = -4542684939965736548L;
    private @Getter final long id;
    private @Getter @Setter String nickname;
    private @Getter @Setter String hashedPassword;
    private @Getter final List<Long> friendsIds;
    private @Getter final Timestamp dateJoined;

    public UserInfo(long userID, String userNickname, String userHashedPassword, Timestamp date) {
        id = userID;
        nickname = userNickname;
        hashedPassword = userHashedPassword;
        friendsIds = new ArrayList<>();
        dateJoined = date;
    }

    public void addFriend(UserInfo u) {
        if (!friendsIds.contains(u.id)) friendsIds.add(u.id);
    }

    public void addFriend(long id) {
        if (!friendsIds.contains(id)) friendsIds.add(id);
    }

    public void removeFriend(UserInfo u) {
        friendsIds.remove(u.id);
    }

    public void removeFriend(long id) {
        friendsIds.remove(id);
    }

    /*
     * auto generated by intellij
     * **************************
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        UserInfo userInfo = (UserInfo) o;
        return id == userInfo.id &&
                Objects.equals(nickname, userInfo.nickname);
    }

    @Override
    public String toString() {
        return "UserInfo{" +
                "id=" + id +
                ", nickname='" + nickname + '\'' +
                ", hashedPassword='" + hashedPassword + '\'' +
                ", dateJoined=" + dateJoined +
                '}';
    }
    /*
     * **************************
     */

}
