package com.github.jacekpoz.server;

import com.github.jacekpoz.common.Chat;
import com.github.jacekpoz.common.Sendable;
import com.github.jacekpoz.common.User;
import com.github.jacekpoz.common.database.queries.Query;
import com.github.jacekpoz.common.database.results.Result;
import com.google.gson.Gson;
import lombok.Getter;
import lombok.Setter;

import java.io.*;
import java.net.Socket;
import java.net.SocketException;
import java.util.Objects;

public class ChatWorker extends Thread {

    @Getter
    private final Socket clientSocket;
    @Getter
    private final Server server;
    @Getter @Setter
    private User currentUser;
    @Getter @Setter
    private Chat currentChat;
    private final PrintWriter out;
    private final BufferedReader in;

    private final Gson gson;

    public ChatWorker(Socket so, Server se) throws IOException {
        super("ChatThread");
        clientSocket = so;
        server = se;
        out = new PrintWriter(clientSocket.getOutputStream());
        in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
        gson = new Gson();
    }

    @Override
    public void run() {
        String inputJSON;
        Result output;
        InputHandler ih = new InputHandler(this);
        while (true) {
            try {
                inputJSON = in.readLine();
                Sendable input = gson.fromJson(inputJSON, Sendable.class);

                if (input instanceof Query) {
                    output = ih.handleQuery((Query) input);
                    out.println(gson.toJson(output, output.getClass()));
                } else ih.handleInput(input);

            } catch (SocketException e) {
                System.out.println("Thread disconnected: " + this);
                e.printStackTrace();
                server.getThreads().remove(this);
                try {
                    clientSocket.close();
                } catch (IOException ioe) {
                    ioe.printStackTrace();
                }
                break;
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

    }

    public void send(String json) {
        out.println(json);
    }

    /*
     * auto generated by intellij
     * **************************
     */
    @Override
    public String toString() {
        return "ChatThread{" +
                "user=" + currentUser +
                "}";
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ChatWorker that = (ChatWorker) o;
        return Objects.equals(currentUser, that.currentUser);
    }
    /*
     * **************************
     */

}
