package com.github.jacekpoz.client.gui.screens;

import com.github.jacekpoz.client.gui.ChatWindow;
import com.github.jacekpoz.common.Screen;
import com.github.jacekpoz.common.sendables.Sendable;
import com.github.jacekpoz.common.sendables.User;
import com.github.jacekpoz.common.sendables.database.queries.chat.InsertChatQuery;
import com.github.jacekpoz.common.sendables.database.results.UserResult;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

public class CreateChatsScreen implements Screen {

    public static final int ID = 4;

    private transient final ChatWindow window;

    private List<User> friends;

    private transient JPanel createChatsScreen;
    private transient JButton backToMessagesButton;
    private transient JScrollPane friendsScrollPane;
    private transient JScrollPane addedFriendsScrollPane;
    private transient JList<User> friendsList;
    private transient JList<User> addedFriendsList;
    private transient JButton addButton;
    private transient JButton deleteButton;
    private transient JButton createChatButton;
    private transient JTextField chatNameTextField;
    private transient JLabel chatNameLabel;

    private transient final DefaultListModel<User> friendsListModel;
    private transient final DefaultListModel<User> addedFriendsListModel;

    public CreateChatsScreen(ChatWindow w) {
        window = w;

        friends = new ArrayList<>();

        friendsListModel = new DefaultListModel<>();
        friendsList.setModel(friendsListModel);
        addedFriendsListModel = new DefaultListModel<>();
        addedFriendsList.setModel(addedFriendsListModel);

        backToMessagesButton.addActionListener(e -> window.setScreen(window.getMessageScreen()));

        addButton.addActionListener(e -> {
            List<User> selected = friendsList.getSelectedValuesList();
            if (selected.isEmpty()) return;

            for (User u : selected) {
                friendsListModel.removeElement(u);
                addedFriendsListModel.addElement(u);
            }

            createChatButton.setEnabled(true);
            deleteButton.setEnabled(true);
            if (friendsListModel.isEmpty()) addButton.setEnabled(false);
        });

        deleteButton.addActionListener(e -> {
            List<User> selected = addedFriendsList.getSelectedValuesList();
            if (selected.isEmpty()) return;

            for (User u : selected) {
                addedFriendsListModel.removeElement(u);
                friendsListModel.addElement(u);
            }

            addButton.setEnabled(true);
            if (addedFriendsListModel.isEmpty()) {
                deleteButton.setEnabled(false);
                createChatButton.setEnabled(false);
            }
        });

        createChatButton.addActionListener(e -> {
            String inputName = chatNameTextField.getText();
            List<User> users = new ArrayList<>();
            users.add(window.getClient().getUser());
            for (int i = 0; i < addedFriendsListModel.size(); i++)
                users.add(addedFriendsListModel.get(i));

            String chatName = inputName;
            if (inputName.isEmpty()) {
                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < users.size(); i++) {
                    sb.append(users.get(i).getNickname());
                    if (i < users.size() - 1)
                        sb.append(", ");
                }
                chatName = sb.toString();
            }

            window.send(new InsertChatQuery(chatName, users, getScreenID()));

            window.setScreen(window.getMessageScreen());
            update();
        });
    }

    @Override
    public JPanel getPanel() {
        return createChatsScreen;
    }

    @Override
    public void update() {
        friendsListModel.clear();
        addedFriendsListModel.clear();
        chatNameTextField.setText("");
        for (User u : friends)
            friendsListModel.addElement(u);
        window.getMessageScreen().update();
    }

    @Override
    public void handleSendable(Sendable s) {
        if (s instanceof UserResult) {
            UserResult ur = (UserResult) s;
            friends = ur.get();
        }

        update();
    }

    @Override
    public long getScreenID() {
        return ID;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createChatsScreen = new JPanel();
        createChatsScreen.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 3, new Insets(0, 0, 0, 0), -1, -1));
        createChatsScreen.setBackground(new Color(-12829636));
        createChatsScreen.setForeground(new Color(-1));
        backToMessagesButton = new JButton();
        backToMessagesButton.setBackground(new Color(-12829636));
        backToMessagesButton.setForeground(new Color(-1));
        backToMessagesButton.setText("Powrót");
        createChatsScreen.add(backToMessagesButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        friendsScrollPane = new JScrollPane();
        friendsScrollPane.setBackground(new Color(-12829636));
        friendsScrollPane.setForeground(new Color(-1));
        friendsScrollPane.setHorizontalScrollBarPolicy(31);
        createChatsScreen.add(friendsScrollPane, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        friendsList = new JList();
        friendsList.setBackground(new Color(-12829636));
        friendsList.setForeground(new Color(-1));
        friendsScrollPane.setViewportView(friendsList);
        addedFriendsScrollPane = new JScrollPane();
        addedFriendsScrollPane.setBackground(new Color(-12829636));
        addedFriendsScrollPane.setForeground(new Color(-1));
        addedFriendsScrollPane.setHorizontalScrollBarPolicy(31);
        createChatsScreen.add(addedFriendsScrollPane, new com.intellij.uiDesigner.core.GridConstraints(3, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        addedFriendsList = new JList();
        addedFriendsList.setBackground(new Color(-12829636));
        addedFriendsList.setForeground(new Color(-1));
        addedFriendsScrollPane.setViewportView(addedFriendsList);
        addButton = new JButton();
        addButton.setBackground(new Color(-12829636));
        addButton.setForeground(new Color(-1));
        addButton.setText("Dodaj");
        createChatsScreen.add(addButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deleteButton = new JButton();
        deleteButton.setBackground(new Color(-12829636));
        deleteButton.setEnabled(false);
        deleteButton.setForeground(new Color(-1));
        deleteButton.setText("Usuń");
        createChatsScreen.add(deleteButton, new com.intellij.uiDesigner.core.GridConstraints(2, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        createChatButton = new JButton();
        createChatButton.setBackground(new Color(-12829636));
        createChatButton.setEnabled(false);
        createChatButton.setForeground(new Color(-1));
        createChatButton.setText("Stwórz czat");
        createChatsScreen.add(createChatButton, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        chatNameTextField = new JTextField();
        chatNameTextField.setBackground(new Color(-12829636));
        chatNameTextField.setForeground(new Color(-1));
        chatNameTextField.setText("");
        createChatsScreen.add(chatNameTextField, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        chatNameLabel = new JLabel();
        chatNameLabel.setBackground(new Color(-12829636));
        chatNameLabel.setForeground(new Color(-1));
        chatNameLabel.setText("Nazwa czatu:");
        createChatsScreen.add(chatNameLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        chatNameLabel.setLabelFor(chatNameTextField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return createChatsScreen;
    }
}
