package com.github.jacekpoz.common.sendables;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class Chat implements Serializable, Sendable {
    private static final long serialVersionUID = -8973712096190274407L;
    @Getter
    private final long id;
    @Getter @Setter
    private String name;
    @Getter
    private final List<User> members;
    @Getter
    private final List<Message> messages;
    @Getter
    private final LocalDateTime dateCreated;
    @Getter
    private final long messageCounter;

    public Chat(long chatID, String chatName, LocalDateTime created, long mCounter) {
        id = chatID;
        name = chatName;
        members = new ArrayList<>();
        messages = new ArrayList<>();
        dateCreated = created;
        messageCounter = mCounter;
    }

    public void sortMessages() {
        messages.sort(Comparator.comparingLong(Message::getMessageID));
    }

    /*
     * auto generated by intellij
     * **************************
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Chat that = (Chat) o;
        return id == that.id;
    }

    @Override
    public String toString() {
        return "Chat{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", dateCreated=" + dateCreated +
                '}';
    }
    /*
     * **************************
     */
}
