package com.github.jacekpoz.common.sendables;

import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

public class Message implements Sendable {

    @Getter
    private final long messageID;
    @Getter
    private final long chatID;
    @Getter
    private final long authorID;
    @Getter @Setter
    private String content;
    @Getter
    private final LocalDateTime dateSent;

    public Message(long mID, long cID, long aID, String text, LocalDateTime send) {
        messageID = mID;
        chatID = cID;
        authorID = aID;
        content = text;
        dateSent = send;
    }

    public Message(String text) {
        this(-1, -1, -1, text, LocalDateTime.MIN);
    }

    /*
     * auto generated by intellij
     * **************************
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Message message = (Message) o;
        return messageID == message.messageID && chatID == message.chatID;
    }

    @Override
    public String toString() {
        return "Message{" +
                "messageID=" + messageID +
                ", chatID=" + chatID +
                ", content='" + content + "'" +
                ", sendDate=" + dateSent +
                ", author=" + authorID +
                "}";
    }
    /*
     * **************************
     */
}
