package com.github.jacekpoz.server;

import com.github.jacekpoz.common.Chat;
import com.github.jacekpoz.common.Message;
import com.github.jacekpoz.common.User;
import lombok.Getter;
import lombok.Setter;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.SocketException;
import java.util.Objects;

public class ChatWorker extends Thread {

    @Getter
    private final Socket clientSocket;
    @Getter
    private final Server server;
    @Getter @Setter
    private User currentUser;
    @Getter @Setter
    private Chat currentChat;
    private final ObjectOutputStream out;
    private final ObjectInputStream in;

    public ChatWorker(Socket so, Server se) throws IOException {
        super("ChatThread");
        clientSocket = so;
        server = se;
        out = new ObjectOutputStream(clientSocket.getOutputStream());
        in = new ObjectInputStream(clientSocket.getInputStream());
    }

    @Override
    public void run() {
        Object input;
        ChatProtocol cp = new ChatProtocol(this);
        while (true) {
            try {
                input = in.readObject();
                cp.processInput(input);
            } catch (SocketException e) {
                System.out.println("Thread disconnected: " + this);
                e.printStackTrace();
                server.getThreads().remove(this);
                try {
                    clientSocket.close();
                } catch (IOException ioe) {
                    ioe.printStackTrace();
                }
                break;
            } catch (IOException | ClassNotFoundException e) {
                e.printStackTrace();
            }
        }

    }

    public void send(Message m) throws IOException {
        out.writeObject(m);
    }

    /*
     * auto generated by intellij
     * **************************
     */
    @Override
    public String toString() {
        return "ChatThread{" +
                "user=" + currentUser +
                "}";
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ChatWorker that = (ChatWorker) o;
        return Objects.equals(currentUser, that.currentUser);
    }
    /*
     * **************************
     */

}
